/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bazarSol from "./Bazar.sol";
export type { bazarSol };
import type * as gpxSol from "./gpx.sol";
export type { gpxSol };
import type * as helperContractSol from "./helperContract.sol";
export type { helperContractSol };
import type * as pdxfaucetSol from "./pdxfaucet.sol";
export type { pdxfaucetSol };
import type * as predixtradingSol from "./predixtrading.sol";
export type { predixtradingSol };
