/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPredictionMarket {
  export type MarketInfoStruct = {
    creator: AddressLike;
    question: string;
    category: string;
    endTime: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    totalBacking: BigNumberish;
  };

  export type MarketInfoStructOutput = [
    creator: string,
    question: string,
    category: string,
    endTime: bigint,
    status: bigint,
    outcome: bigint,
    yesPool: bigint,
    noPool: bigint,
    totalBacking: bigint
  ] & {
    creator: string;
    question: string;
    category: string;
    endTime: bigint;
    status: bigint;
    outcome: bigint;
    yesPool: bigint;
    noPool: bigint;
    totalBacking: bigint;
  };

  export type OrderInfoStruct = {
    user: AddressLike;
    marketId: BigNumberish;
    isYes: boolean;
    tokenAmount: BigNumberish;
    stopLossPrice: BigNumberish;
    takeProfitPrice: BigNumberish;
    isActive: boolean;
  };

  export type OrderInfoStructOutput = [
    user: string,
    marketId: bigint,
    isYes: boolean,
    tokenAmount: bigint,
    stopLossPrice: bigint,
    takeProfitPrice: bigint,
    isActive: boolean
  ] & {
    user: string;
    marketId: bigint;
    isYes: boolean;
    tokenAmount: bigint;
    stopLossPrice: bigint;
    takeProfitPrice: bigint;
    isActive: boolean;
  };
}

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyNoWithPDXFor"
      | "buyYesWithPDXFor"
      | "createStopLossOrder"
      | "createTakeProfitOrder"
      | "executeOrder"
      | "getCurrentMultipliers"
      | "getMarketInfo"
      | "getOrderInfo"
      | "getUserOrders"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyNoWithPDXFor",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyYesWithPDXFor",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createStopLossOrder",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTakeProfitOrder",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyNoWithPDXFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyYesWithPDXFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStopLossOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTakeProfitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyNoWithPDXFor: TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buyYesWithPDXFor: TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createStopLossOrder: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createTakeProfitOrder: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executeOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCurrentMultipliers: TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint, bigint, bigint]],
    "view"
  >;

  getMarketInfo: TypedContractMethod<
    [marketId: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;

  getOrderInfo: TypedContractMethod<
    [orderId: BigNumberish],
    [IPredictionMarket.OrderInfoStructOutput],
    "view"
  >;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyNoWithPDXFor"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyYesWithPDXFor"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createStopLossOrder"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTakeProfitOrder"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentMultipliers"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderInfo"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [IPredictionMarket.OrderInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  filters: {};
}
