/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPredictionMarket {
  export type MarketInfoStruct = {
    creator: AddressLike;
    question: string;
    category: string;
    endTime: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    totalBacking: BigNumberish;
  };

  export type MarketInfoStructOutput = [
    creator: string,
    question: string,
    category: string,
    endTime: bigint,
    status: bigint,
    outcome: bigint,
    yesPool: bigint,
    noPool: bigint,
    totalBacking: bigint
  ] & {
    creator: string;
    question: string;
    category: string;
    endTime: bigint;
    status: bigint;
    outcome: bigint;
    yesPool: bigint;
    noPool: bigint;
    totalBacking: bigint;
  };

  export type OrderInfoStruct = {
    user: AddressLike;
    marketId: BigNumberish;
    isYes: boolean;
    tokenAmount: BigNumberish;
    stopLossPrice: BigNumberish;
    takeProfitPrice: BigNumberish;
    isActive: boolean;
  };

  export type OrderInfoStructOutput = [
    user: string,
    marketId: bigint,
    isYes: boolean,
    tokenAmount: bigint,
    stopLossPrice: bigint,
    takeProfitPrice: bigint,
    isActive: boolean
  ] & {
    user: string;
    marketId: bigint;
    isYes: boolean;
    tokenAmount: bigint;
    stopLossPrice: bigint;
    takeProfitPrice: bigint;
    isActive: boolean;
  };
}

export interface PredictionMarketPDXInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "buyNoWithPDXFor"
      | "buyYesWithPDXFor"
      | "cancelOrder"
      | "checkOrderTrigger"
      | "claimRedemption"
      | "createMarket"
      | "createStopLossOrder"
      | "createTakeProfitOrder"
      | "executeOrder"
      | "feeBps"
      | "getBuyNoOutput"
      | "getBuyYesOutput"
      | "getCurrentMultipliers"
      | "getMarketInfo"
      | "getOrderInfo"
      | "getUserOrders"
      | "lpBalances"
      | "lpFeeBps"
      | "markets"
      | "nextMarketId"
      | "nextOrderId"
      | "orders"
      | "owner"
      | "pdxToken"
      | "removeLiquidity"
      | "requestResolution"
      | "resolutionServer"
      | "resolveMarket"
      | "sellNoForPDX"
      | "sellYesForPDX"
      | "userInvestments"
      | "userOrders"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuyWithPDX"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "MarketCreated"
      | "MarketResolved"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderExecuted"
      | "RedemptionClaimed"
      | "ResolutionRequested"
      | "SellForPDX"
      | "Swap"
      | "UserInvestmentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNoWithPDXFor",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyYesWithPDXFor",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkOrderTrigger",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createStopLossOrder",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTakeProfitOrder",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBuyNoOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyYesOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lpFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pdxToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolution",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellNoForPDX",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellYesForPDX",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userInvestments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyNoWithPDXFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyYesWithPDXFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkOrderTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStopLossOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTakeProfitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyNoOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyYesOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpBalances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pdxToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellNoForPDX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellYesForPDX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace BuyWithPDXEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    buyYes: boolean,
    pdxIn: BigNumberish,
    tokenOut: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    buyYes: boolean,
    pdxIn: bigint,
    tokenOut: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    buyYes: boolean;
    pdxIn: bigint;
    tokenOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    category: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    category: string,
    yesToken: string,
    noToken: string,
    endTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    category: string;
    yesToken: string;
    noToken: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    id: BigNumberish,
    outcome: BigNumberish,
    reason: string,
    confidence: BigNumberish,
    resolvedBy: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    outcome: bigint,
    reason: string,
    confidence: bigint,
    resolvedBy: string
  ];
  export interface OutputObject {
    id: bigint;
    outcome: bigint;
    reason: string;
    confidence: bigint;
    resolvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    marketId: BigNumberish
  ];
  export type OutputTuple = [orderId: bigint, user: string, marketId: bigint];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    marketId: BigNumberish,
    orderType: BigNumberish,
    isYes: boolean,
    tokenAmount: BigNumberish,
    triggerPrice: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    user: string,
    marketId: bigint,
    orderType: bigint,
    isYes: boolean,
    tokenAmount: bigint,
    triggerPrice: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    marketId: bigint;
    orderType: bigint;
    isYes: boolean;
    tokenAmount: bigint;
    triggerPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExecutedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    marketId: BigNumberish,
    amountReceived: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    user: string,
    marketId: bigint,
    amountReceived: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    marketId: bigint;
    amountReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionClaimedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amountClaimed: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, amountClaimed: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    amountClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionRequestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    requester: AddressLike,
    requestedAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    requester: string,
    requestedAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    requester: string;
    requestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellForPDXEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    sellYes: boolean,
    tokenIn: BigNumberish,
    pdxOut: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    sellYes: boolean,
    tokenIn: bigint,
    pdxOut: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    sellYes: boolean;
    tokenIn: bigint;
    pdxOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    yesIn: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    yesIn: boolean,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    yesIn: boolean;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserInvestmentUpdatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    totalInvested: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    totalInvested: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    totalInvested: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketPDX extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketPDX;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketPDXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [id: BigNumberish, yesAmount: BigNumberish, noAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyNoWithPDXFor: TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buyYesWithPDXFor: TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkOrderTrigger: TypedContractMethod<
    [orderId: BigNumberish],
    [[boolean, bigint, bigint]],
    "view"
  >;

  claimRedemption: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createStopLossOrder: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createTakeProfitOrder: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executeOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  getBuyNoOutput: TypedContractMethod<
    [id: BigNumberish, pdxAmount: BigNumberish],
    [[bigint, bigint] & { totalNoOut: bigint; totalFee: bigint }],
    "view"
  >;

  getBuyYesOutput: TypedContractMethod<
    [id: BigNumberish, pdxAmount: BigNumberish],
    [[bigint, bigint] & { totalYesOut: bigint; totalFee: bigint }],
    "view"
  >;

  getCurrentMultipliers: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;

  getMarketInfo: TypedContractMethod<
    [id: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;

  getOrderInfo: TypedContractMethod<
    [id: BigNumberish],
    [IPredictionMarket.OrderInfoStructOutput],
    "view"
  >;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  lpBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  lpFeeBps: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        orderId: bigint;
        user: string;
        marketId: bigint;
        isYes: boolean;
        tokenAmount: bigint;
        triggerPrice: bigint;
        orderType: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pdxToken: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [id: BigNumberish, lpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestResolution: TypedContractMethod<
    [id: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  resolutionServer: TypedContractMethod<[], [string], "view">;

  resolveMarket: TypedContractMethod<
    [
      id: BigNumberish,
      outcomeIndex: BigNumberish,
      reason: string,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  sellNoForPDX: TypedContractMethod<
    [id: BigNumberish, tokenAmount: BigNumberish, minPDXOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  sellYesForPDX: TypedContractMethod<
    [id: BigNumberish, tokenAmount: BigNumberish, minPDXOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  userInvestments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawPlatformFees: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [id: BigNumberish, yesAmount: BigNumberish, noAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyNoWithPDXFor"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyYesWithPDXFor"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkOrderTrigger"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [[boolean, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRedemption"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createStopLossOrder"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTakeProfitOrder"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBuyNoOutput"
  ): TypedContractMethod<
    [id: BigNumberish, pdxAmount: BigNumberish],
    [[bigint, bigint] & { totalNoOut: bigint; totalFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyYesOutput"
  ): TypedContractMethod<
    [id: BigNumberish, pdxAmount: BigNumberish],
    [[bigint, bigint] & { totalYesOut: bigint; totalFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentMultipliers"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IPredictionMarket.OrderInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "lpBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        orderId: bigint;
        user: string;
        marketId: bigint;
        isYes: boolean;
        tokenAmount: bigint;
        triggerPrice: bigint;
        orderType: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pdxToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [id: BigNumberish, lpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestResolution"
  ): TypedContractMethod<
    [id: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolutionServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      outcomeIndex: BigNumberish,
      reason: string,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellNoForPDX"
  ): TypedContractMethod<
    [id: BigNumberish, tokenAmount: BigNumberish, minPDXOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellYesForPDX"
  ): TypedContractMethod<
    [id: BigNumberish, tokenAmount: BigNumberish, minPDXOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userInvestments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BuyWithPDX"
  ): TypedContractEvent<
    BuyWithPDXEvent.InputTuple,
    BuyWithPDXEvent.OutputTuple,
    BuyWithPDXEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExecuted"
  ): TypedContractEvent<
    OrderExecutedEvent.InputTuple,
    OrderExecutedEvent.OutputTuple,
    OrderExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionClaimed"
  ): TypedContractEvent<
    RedemptionClaimedEvent.InputTuple,
    RedemptionClaimedEvent.OutputTuple,
    RedemptionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionRequested"
  ): TypedContractEvent<
    ResolutionRequestedEvent.InputTuple,
    ResolutionRequestedEvent.OutputTuple,
    ResolutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SellForPDX"
  ): TypedContractEvent<
    SellForPDXEvent.InputTuple,
    SellForPDXEvent.OutputTuple,
    SellForPDXEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "UserInvestmentUpdated"
  ): TypedContractEvent<
    UserInvestmentUpdatedEvent.InputTuple,
    UserInvestmentUpdatedEvent.OutputTuple,
    UserInvestmentUpdatedEvent.OutputObject
  >;

  filters: {
    "BuyWithPDX(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      BuyWithPDXEvent.InputTuple,
      BuyWithPDXEvent.OutputTuple,
      BuyWithPDXEvent.OutputObject
    >;
    BuyWithPDX: TypedContractEvent<
      BuyWithPDXEvent.InputTuple,
      BuyWithPDXEvent.OutputTuple,
      BuyWithPDXEvent.OutputObject
    >;

    "LiquidityAdded(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "MarketCreated(uint256,string,string,address,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,string,uint256,address)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OrderCancelled(uint256,address,uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,uint256,uint8,bool,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;
    OrderExecuted: TypedContractEvent<
      OrderExecutedEvent.InputTuple,
      OrderExecutedEvent.OutputTuple,
      OrderExecutedEvent.OutputObject
    >;

    "RedemptionClaimed(uint256,address,uint256)": TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;
    RedemptionClaimed: TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;

    "ResolutionRequested(uint256,address,uint256)": TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
    ResolutionRequested: TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;

    "SellForPDX(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      SellForPDXEvent.InputTuple,
      SellForPDXEvent.OutputTuple,
      SellForPDXEvent.OutputObject
    >;
    SellForPDX: TypedContractEvent<
      SellForPDXEvent.InputTuple,
      SellForPDXEvent.OutputTuple,
      SellForPDXEvent.OutputObject
    >;

    "Swap(uint256,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "UserInvestmentUpdated(uint256,address,uint256,uint256)": TypedContractEvent<
      UserInvestmentUpdatedEvent.InputTuple,
      UserInvestmentUpdatedEvent.OutputTuple,
      UserInvestmentUpdatedEvent.OutputObject
    >;
    UserInvestmentUpdated: TypedContractEvent<
      UserInvestmentUpdatedEvent.InputTuple,
      UserInvestmentUpdatedEvent.OutputTuple,
      UserInvestmentUpdatedEvent.OutputObject
    >;
  };
}
