/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPredictionMarket {
  export type MarketInfoStruct = {
    creator: AddressLike;
    question: string;
    category: string;
    endTime: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    totalBacking: BigNumberish;
  };

  export type MarketInfoStructOutput = [
    creator: string,
    question: string,
    category: string,
    endTime: bigint,
    status: bigint,
    outcome: bigint,
    yesPool: bigint,
    noPool: bigint,
    totalBacking: bigint
  ] & {
    creator: string;
    question: string;
    category: string;
    endTime: bigint;
    status: bigint;
    outcome: bigint;
    yesPool: bigint;
    noPool: bigint;
    totalBacking: bigint;
  };
}

export interface TradingBotInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoBuyNo"
      | "autoBuyYes"
      | "batchMonitorOrders"
      | "createStopLossForUser"
      | "createTakeProfitForUser"
      | "getMarketData"
      | "getMultipliers"
      | "getUserOrders"
      | "monitorAndExecuteOrder"
      | "owner"
      | "predictionMarket"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AutoTradeExecuted" | "OrderMonitored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autoBuyNo",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoBuyYes",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMonitorOrders",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createStopLossForUser",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTakeProfitForUser",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monitorAndExecuteOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionMarket",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "autoBuyNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "autoBuyYes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchMonitorOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStopLossForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTakeProfitForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorAndExecuteOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionMarket",
    data: BytesLike
  ): Result;
}

export namespace AutoTradeExecutedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    isYes: boolean,
    amount: BigNumberish,
    tokensReceived: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    isYes: boolean,
    amount: bigint,
    tokensReceived: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    isYes: boolean;
    amount: bigint;
    tokensReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderMonitoredEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    shouldExecute: boolean,
    currentPrice: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    shouldExecute: boolean,
    currentPrice: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    shouldExecute: boolean;
    currentPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradingBot extends BaseContract {
  connect(runner?: ContractRunner | null): TradingBot;
  waitForDeployment(): Promise<this>;

  interface: TradingBotInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoBuyNo: TypedContractMethod<
    [
      marketId: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  autoBuyYes: TypedContractMethod<
    [
      marketId: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  batchMonitorOrders: TypedContractMethod<
    [orderIds: BigNumberish[]],
    [boolean[]],
    "view"
  >;

  createStopLossForUser: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createTakeProfitForUser: TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getMarketData: TypedContractMethod<
    [marketId: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;

  getMultipliers: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  monitorAndExecuteOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictionMarket: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoBuyNo"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      beneficiary: AddressLike,
      minNoOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "autoBuyYes"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      beneficiary: AddressLike,
      minYesOut: BigNumberish,
      pdxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchMonitorOrders"
  ): TypedContractMethod<[orderIds: BigNumberish[]], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "createStopLossForUser"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      stopLossPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTakeProfitForUser"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      isYes: boolean,
      tokenAmount: BigNumberish,
      takeProfitPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarketData"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [IPredictionMarket.MarketInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMultipliers"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "monitorAndExecuteOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictionMarket"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AutoTradeExecuted"
  ): TypedContractEvent<
    AutoTradeExecutedEvent.InputTuple,
    AutoTradeExecutedEvent.OutputTuple,
    AutoTradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OrderMonitored"
  ): TypedContractEvent<
    OrderMonitoredEvent.InputTuple,
    OrderMonitoredEvent.OutputTuple,
    OrderMonitoredEvent.OutputObject
  >;

  filters: {
    "AutoTradeExecuted(uint256,bool,uint256,uint256)": TypedContractEvent<
      AutoTradeExecutedEvent.InputTuple,
      AutoTradeExecutedEvent.OutputTuple,
      AutoTradeExecutedEvent.OutputObject
    >;
    AutoTradeExecuted: TypedContractEvent<
      AutoTradeExecutedEvent.InputTuple,
      AutoTradeExecutedEvent.OutputTuple,
      AutoTradeExecutedEvent.OutputObject
    >;

    "OrderMonitored(uint256,bool,uint256)": TypedContractEvent<
      OrderMonitoredEvent.InputTuple,
      OrderMonitoredEvent.OutputTuple,
      OrderMonitoredEvent.OutputObject
    >;
    OrderMonitored: TypedContractEvent<
      OrderMonitoredEvent.InputTuple,
      OrderMonitoredEvent.OutputTuple,
      OrderMonitoredEvent.OutputObject
    >;
  };
}
