/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPredictionMarketCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "feeBps"
      | "lpFeeBps"
      | "markets"
      | "nextMarketId"
      | "userInvestments"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userInvestments",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userInvestments",
    data: BytesLike
  ): Result;
}

export interface IPredictionMarketCore extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarketCore;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  lpFeeBps: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  userInvestments: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userInvestments"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;

  filters: {};
}
