/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarketHelper {
  export type UserPositionStruct = {
    marketId: BigNumberish;
    yesBalance: BigNumberish;
    noBalance: BigNumberish;
    totalInvested: BigNumberish;
    bnbInvested: BigNumberish;
  };

  export type UserPositionStructOutput = [
    marketId: bigint,
    yesBalance: bigint,
    noBalance: bigint,
    totalInvested: bigint,
    bnbInvested: bigint
  ] & {
    marketId: bigint;
    yesBalance: bigint;
    noBalance: bigint;
    totalInvested: bigint;
    bnbInvested: bigint;
  };

  export type TradingInfoStruct = {
    yesMultiplier: BigNumberish;
    noMultiplier: BigNumberish;
    yesPrice: BigNumberish;
    noPrice: BigNumberish;
    totalLiquidity: BigNumberish;
  };

  export type TradingInfoStructOutput = [
    yesMultiplier: bigint,
    noMultiplier: bigint,
    yesPrice: bigint,
    noPrice: bigint,
    totalLiquidity: bigint
  ] & {
    yesMultiplier: bigint;
    noMultiplier: bigint;
    yesPrice: bigint;
    noPrice: bigint;
    totalLiquidity: bigint;
  };
}

export interface PredictionMarketHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_checkPosition"
      | "_getPosition"
      | "_getTradingInfoSafe"
      | "batchGetMarketInvestments"
      | "batchGetTradingInfo"
      | "canDispute"
      | "canRequestResolution"
      | "getBuyNoMultiplier"
      | "getBuyYesMultiplier"
      | "getCurrentMultipliers"
      | "getMarketInvestment"
      | "getNoPrice"
      | "getSwapMultiplier"
      | "getTradingInfo"
      | "getUserPositions"
      | "getUserTotalInvestment"
      | "getYesPrice"
      | "predictionMarket"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_checkPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_getPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_getTradingInfoSafe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetMarketInvestments",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetTradingInfo",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canRequestResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyNoMultiplier",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyYesMultiplier",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInvestment",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNoPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapMultiplier",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalInvestment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYesPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictionMarket",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_checkPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_getTradingInfoSafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetMarketInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetTradingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canRequestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyNoMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyYesMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNoPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSwapMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYesPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictionMarket",
    data: BytesLike
  ): Result;
}

export interface PredictionMarketHelper extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketHelper;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _checkPosition: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  _getPosition: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [PredictionMarketHelper.UserPositionStructOutput],
    "view"
  >;

  _getTradingInfoSafe: TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketHelper.TradingInfoStructOutput],
    "view"
  >;

  batchGetMarketInvestments: TypedContractMethod<
    [marketId: BigNumberish, users: AddressLike[]],
    [bigint[]],
    "view"
  >;

  batchGetTradingInfo: TypedContractMethod<
    [marketIds: BigNumberish[]],
    [PredictionMarketHelper.TradingInfoStructOutput[]],
    "view"
  >;

  canDispute: TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;

  canRequestResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [boolean],
    "view"
  >;

  getBuyNoMultiplier: TypedContractMethod<
    [marketId: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;

  getBuyYesMultiplier: TypedContractMethod<
    [marketId: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;

  getCurrentMultipliers: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;

  getMarketInvestment: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getNoPrice: TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;

  getSwapMultiplier: TypedContractMethod<
    [marketId: BigNumberish, amountIn: BigNumberish, isYesIn: boolean],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        amountOut: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;

  getTradingInfo: TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketHelper.TradingInfoStructOutput],
    "view"
  >;

  getUserPositions: TypedContractMethod<
    [user: AddressLike],
    [PredictionMarketHelper.UserPositionStructOutput[]],
    "view"
  >;

  getUserTotalInvestment: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getYesPrice: TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;

  predictionMarket: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_checkPosition"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "_getPosition"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [PredictionMarketHelper.UserPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "_getTradingInfoSafe"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketHelper.TradingInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchGetMarketInvestments"
  ): TypedContractMethod<
    [marketId: BigNumberish, users: AddressLike[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchGetTradingInfo"
  ): TypedContractMethod<
    [marketIds: BigNumberish[]],
    [PredictionMarketHelper.TradingInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "canDispute"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "canRequestResolution"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBuyNoMultiplier"
  ): TypedContractMethod<
    [marketId: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyYesMultiplier"
  ): TypedContractMethod<
    [marketId: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentMultipliers"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketInvestment"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNoPrice"
  ): TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSwapMultiplier"
  ): TypedContractMethod<
    [marketId: BigNumberish, amountIn: BigNumberish, isYesIn: boolean],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        amountOut: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTradingInfo"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketHelper.TradingInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<
    [user: AddressLike],
    [PredictionMarketHelper.UserPositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTotalInvestment"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getYesPrice"
  ): TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictionMarket"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
