/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarket__factory>;
    getContractFactory(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OutcomeToken__factory>;
    getContractFactory(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers__factory>;
    getContractFactory(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TradingBot__factory>;
    getContractFactory(
      name: "GPXToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GPXToken__factory>;
    getContractFactory(
      name: "IOutcomeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOutcomeToken__factory>;
    getContractFactory(
      name: "IPredictionMarketCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarketCore__factory>;
    getContractFactory(
      name: "PredictionMarketHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketHelper__factory>;
    getContractFactory(
      name: "PDXFaucet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PDXFaucet__factory>;
    getContractFactory(
      name: "IPDX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPDX__factory>;
    getContractFactory(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarket__factory>;
    getContractFactory(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OutcomeToken__factory>;
    getContractFactory(
      name: "PredictionMarketPDX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketPDX__factory>;
    getContractFactory(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers__factory>;
    getContractFactory(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TradingBot__factory>;
    getContractFactory(
      name: "TradingBotPDX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TradingBotPDX__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IPredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarket>;
    getContractAt(
      name: "OutcomeToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OutcomeToken>;
    getContractAt(
      name: "PredictionMarketWithMultipliers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    getContractAt(
      name: "TradingBot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TradingBot>;
    getContractAt(
      name: "GPXToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GPXToken>;
    getContractAt(
      name: "IOutcomeToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOutcomeToken>;
    getContractAt(
      name: "IPredictionMarketCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarketCore>;
    getContractAt(
      name: "PredictionMarketHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketHelper>;
    getContractAt(
      name: "PDXFaucet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PDXFaucet>;
    getContractAt(
      name: "IPDX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPDX>;
    getContractAt(
      name: "IPredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarket>;
    getContractAt(
      name: "OutcomeToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OutcomeToken>;
    getContractAt(
      name: "PredictionMarketPDX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketPDX>;
    getContractAt(
      name: "PredictionMarketWithMultipliers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    getContractAt(
      name: "TradingBot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TradingBot>;
    getContractAt(
      name: "TradingBotPDX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TradingBotPDX>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Burnable>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "GPXToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GPXToken>;
    deployContract(
      name: "IOutcomeToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeToken>;
    deployContract(
      name: "IPredictionMarketCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarketCore>;
    deployContract(
      name: "PredictionMarketHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketHelper>;
    deployContract(
      name: "PDXFaucet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PDXFaucet>;
    deployContract(
      name: "IPDX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPDX>;
    deployContract(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketPDX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketPDX>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "TradingBotPDX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBotPDX>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Burnable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Burnable>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IPredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "GPXToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GPXToken>;
    deployContract(
      name: "IOutcomeToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeToken>;
    deployContract(
      name: "IPredictionMarketCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarketCore>;
    deployContract(
      name: "PredictionMarketHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketHelper>;
    deployContract(
      name: "PDXFaucet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PDXFaucet>;
    deployContract(
      name: "IPDX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPDX>;
    deployContract(
      name: "IPredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketPDX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketPDX>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "TradingBotPDX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBotPDX>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
