/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarket__factory>;
    getContractFactory(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OutcomeToken__factory>;
    getContractFactory(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers__factory>;
    getContractFactory(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TradingBot__factory>;
    getContractFactory(
      name: "IOutcomeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOutcomeToken__factory>;
    getContractFactory(
      name: "IPredictionMarketCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarketCore__factory>;
    getContractFactory(
      name: "PredictionMarketHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarketHelper__factory>;

    getContractAt(
      name: "IPredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarket>;
    getContractAt(
      name: "OutcomeToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OutcomeToken>;
    getContractAt(
      name: "PredictionMarketWithMultipliers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    getContractAt(
      name: "TradingBot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TradingBot>;
    getContractAt(
      name: "IOutcomeToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOutcomeToken>;
    getContractAt(
      name: "IPredictionMarketCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarketCore>;
    getContractAt(
      name: "PredictionMarketHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarketHelper>;

    deployContract(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "IOutcomeToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeToken>;
    deployContract(
      name: "IPredictionMarketCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarketCore>;
    deployContract(
      name: "PredictionMarketHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketHelper>;

    deployContract(
      name: "IPredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "OutcomeToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OutcomeToken>;
    deployContract(
      name: "PredictionMarketWithMultipliers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketWithMultipliers>;
    deployContract(
      name: "TradingBot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TradingBot>;
    deployContract(
      name: "IOutcomeToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOutcomeToken>;
    deployContract(
      name: "IPredictionMarketCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarketCore>;
    deployContract(
      name: "PredictionMarketHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarketHelper>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
