/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PredictionMarketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_PERIOD"
      | "DISPUTE_BOND"
      | "MINIMUM_LIQUIDITY"
      | "MIN_INITIAL_LIQUIDITY"
      | "PROPOSAL_BOND"
      | "addLiquidity"
      | "addOracle"
      | "burnCompleteSets"
      | "closeMarket"
      | "createMarket"
      | "disputeProposal"
      | "emergencyResolve"
      | "feeBps"
      | "finalizeProposal"
      | "getAmountOut"
      | "getLPBalance"
      | "getMarket"
      | "getOracleVotes"
      | "getOracles"
      | "getPrice"
      | "getProposalInfo"
      | "isOracle"
      | "lpBalances"
      | "lpFeeBps"
      | "markets"
      | "mintCompleteSets"
      | "nextMarketId"
      | "oracleVote"
      | "oracleVotes"
      | "oracles"
      | "outcomeVoteCount"
      | "owner"
      | "proposeOutcome"
      | "redeem"
      | "removeLiquidity"
      | "removeOracle"
      | "requiredOracleVotes"
      | "setFees"
      | "swapNoForYes"
      | "swapYesForNo"
      | "transferOwnership"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompleteSetBurned"
      | "CompleteSetMinted"
      | "FeesWithdrawn"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "MarketClosed"
      | "MarketCreated"
      | "OracleAdded"
      | "OracleRemoved"
      | "OracleVoted"
      | "OutcomeProposed"
      | "ProposalDisputed"
      | "Redeemed"
      | "Resolved"
      | "Swap"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INITIAL_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnCompleteSets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyResolve",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lpFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCompleteSets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleVotes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outcomeVoteCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeOutcome",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredOracleVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapNoForYes",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapYesForNo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INITIAL_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnCompleteSets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLPBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOracleVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpBalances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintCompleteSets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracleVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "outcomeVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredOracleVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapNoForYes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapYesForNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CompleteSetBurnedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompleteSetMintedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    yesToken: string,
    noToken: string,
    endTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    yesToken: string;
    noToken: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleAddedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRemovedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleVotedEvent {
  export type InputTuple = [
    id: BigNumberish,
    oracle: AddressLike,
    outcome: BigNumberish
  ];
  export type OutputTuple = [id: bigint, oracle: string, outcome: bigint];
  export interface OutputObject {
    id: bigint;
    oracle: string;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeProposedEvent {
  export type InputTuple = [
    id: BigNumberish,
    proposer: AddressLike,
    outcome: BigNumberish,
    bond: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    proposer: string,
    outcome: bigint,
    bond: bigint
  ];
  export interface OutputObject {
    id: bigint;
    proposer: string;
    outcome: bigint;
    bond: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalDisputedEvent {
  export type InputTuple = [
    id: BigNumberish,
    disputer: AddressLike,
    bond: BigNumberish
  ];
  export type OutputTuple = [id: bigint, disputer: string, bond: bigint];
  export interface OutputObject {
    id: bigint;
    disputer: string;
    bond: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    amount: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolvedEvent {
  export type InputTuple = [id: BigNumberish, outcome: BigNumberish];
  export type OutputTuple = [id: bigint, outcome: bigint];
  export interface OutputObject {
    id: bigint;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    yesIn: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    yesIn: boolean,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    yesIn: boolean;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketFactory;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_BOND: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  MIN_INITIAL_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_BOND: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [
      id: BigNumberish,
      yesAmount: BigNumberish,
      noAmount: BigNumberish,
      minLPTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  addOracle: TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;

  burnCompleteSets: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeMarket: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  createMarket: TypedContractMethod<
    [
      question: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  disputeProposal: TypedContractMethod<[id: BigNumberish], [void], "payable">;

  emergencyResolve: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  finalizeProposal: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAmountOut: TypedContractMethod<
    [id: BigNumberish, amountIn: BigNumberish, yesIn: boolean],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "view"
  >;

  getLPBalance: TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getMarket: TypedContractMethod<
    [id: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
      }
    ],
    "view"
  >;

  getOracleVotes: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        yesVotes: bigint;
        noVotes: bigint;
        invalidVotes: bigint;
      }
    ],
    "view"
  >;

  getOracles: TypedContractMethod<[], [string[]], "view">;

  getPrice: TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint] & { yesPrice: bigint; noPrice: bigint }],
    "view"
  >;

  getProposalInfo: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        proposer: string;
        proposedOutcome: bigint;
        proposalTime: bigint;
        proposalBond: bigint;
        disputer: string;
        disputeBond: bigint;
      }
    ],
    "view"
  >;

  isOracle: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lpBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  lpFeeBps: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        proposer: string;
        proposedOutcome: bigint;
        proposalTime: bigint;
        proposalBond: bigint;
        disputeBond: bigint;
        disputer: string;
      }
    ],
    "view"
  >;

  mintCompleteSets: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  oracleVote: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  oracleVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  oracles: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  outcomeVoteCount: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposeOutcome: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;

  redeem: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  removeLiquidity: TypedContractMethod<
    [
      id: BigNumberish,
      lpTokens: BigNumberish,
      minYes: BigNumberish,
      minNo: BigNumberish
    ],
    [[bigint, bigint] & { yesAmount: bigint; noAmount: bigint }],
    "nonpayable"
  >;

  removeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredOracleVotes: TypedContractMethod<[], [bigint], "view">;

  setFees: TypedContractMethod<
    [newFeeBps: BigNumberish, newLpFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapNoForYes: TypedContractMethod<
    [id: BigNumberish, noIn: BigNumberish, minYesOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapYesForNo: TypedContractMethod<
    [id: BigNumberish, yesIn: BigNumberish, minNoOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INITIAL_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      yesAmount: BigNumberish,
      noAmount: BigNumberish,
      minLPTokens: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnCompleteSets"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeMarket"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeProposal"
  ): TypedContractMethod<[id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyResolve"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeProposal"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [id: BigNumberish, amountIn: BigNumberish, yesIn: boolean],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLPBalance"
  ): TypedContractMethod<
    [id: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracleVotes"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        yesVotes: bigint;
        noVotes: bigint;
        invalidVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint] & { yesPrice: bigint; noPrice: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        proposer: string;
        proposedOutcome: bigint;
        proposalTime: bigint;
        proposalBond: bigint;
        disputer: string;
        disputeBond: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOracle"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lpBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        proposer: string;
        proposedOutcome: bigint;
        proposalTime: bigint;
        proposalBond: bigint;
        disputeBond: bigint;
        disputer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCompleteSets"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleVote"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracleVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracles"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "outcomeVoteCount"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeOutcome"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      lpTokens: BigNumberish,
      minYes: BigNumberish,
      minNo: BigNumberish
    ],
    [[bigint, bigint] & { yesAmount: bigint; noAmount: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredOracleVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [newFeeBps: BigNumberish, newLpFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapNoForYes"
  ): TypedContractMethod<
    [id: BigNumberish, noIn: BigNumberish, minYesOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapYesForNo"
  ): TypedContractMethod<
    [id: BigNumberish, yesIn: BigNumberish, minNoOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CompleteSetBurned"
  ): TypedContractEvent<
    CompleteSetBurnedEvent.InputTuple,
    CompleteSetBurnedEvent.OutputTuple,
    CompleteSetBurnedEvent.OutputObject
  >;
  getEvent(
    key: "CompleteSetMinted"
  ): TypedContractEvent<
    CompleteSetMintedEvent.InputTuple,
    CompleteSetMintedEvent.OutputTuple,
    CompleteSetMintedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleAdded"
  ): TypedContractEvent<
    OracleAddedEvent.InputTuple,
    OracleAddedEvent.OutputTuple,
    OracleAddedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRemoved"
  ): TypedContractEvent<
    OracleRemovedEvent.InputTuple,
    OracleRemovedEvent.OutputTuple,
    OracleRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OracleVoted"
  ): TypedContractEvent<
    OracleVotedEvent.InputTuple,
    OracleVotedEvent.OutputTuple,
    OracleVotedEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeProposed"
  ): TypedContractEvent<
    OutcomeProposedEvent.InputTuple,
    OutcomeProposedEvent.OutputTuple,
    OutcomeProposedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalDisputed"
  ): TypedContractEvent<
    ProposalDisputedEvent.InputTuple,
    ProposalDisputedEvent.OutputTuple,
    ProposalDisputedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Resolved"
  ): TypedContractEvent<
    ResolvedEvent.InputTuple,
    ResolvedEvent.OutputTuple,
    ResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "CompleteSetBurned(uint256,address,uint256)": TypedContractEvent<
      CompleteSetBurnedEvent.InputTuple,
      CompleteSetBurnedEvent.OutputTuple,
      CompleteSetBurnedEvent.OutputObject
    >;
    CompleteSetBurned: TypedContractEvent<
      CompleteSetBurnedEvent.InputTuple,
      CompleteSetBurnedEvent.OutputTuple,
      CompleteSetBurnedEvent.OutputObject
    >;

    "CompleteSetMinted(uint256,address,uint256)": TypedContractEvent<
      CompleteSetMintedEvent.InputTuple,
      CompleteSetMintedEvent.OutputTuple,
      CompleteSetMintedEvent.OutputObject
    >;
    CompleteSetMinted: TypedContractEvent<
      CompleteSetMintedEvent.InputTuple,
      CompleteSetMintedEvent.OutputTuple,
      CompleteSetMintedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "LiquidityAdded(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "MarketClosed(uint256)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(uint256,string,address,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "OracleAdded(address)": TypedContractEvent<
      OracleAddedEvent.InputTuple,
      OracleAddedEvent.OutputTuple,
      OracleAddedEvent.OutputObject
    >;
    OracleAdded: TypedContractEvent<
      OracleAddedEvent.InputTuple,
      OracleAddedEvent.OutputTuple,
      OracleAddedEvent.OutputObject
    >;

    "OracleRemoved(address)": TypedContractEvent<
      OracleRemovedEvent.InputTuple,
      OracleRemovedEvent.OutputTuple,
      OracleRemovedEvent.OutputObject
    >;
    OracleRemoved: TypedContractEvent<
      OracleRemovedEvent.InputTuple,
      OracleRemovedEvent.OutputTuple,
      OracleRemovedEvent.OutputObject
    >;

    "OracleVoted(uint256,address,uint8)": TypedContractEvent<
      OracleVotedEvent.InputTuple,
      OracleVotedEvent.OutputTuple,
      OracleVotedEvent.OutputObject
    >;
    OracleVoted: TypedContractEvent<
      OracleVotedEvent.InputTuple,
      OracleVotedEvent.OutputTuple,
      OracleVotedEvent.OutputObject
    >;

    "OutcomeProposed(uint256,address,uint8,uint256)": TypedContractEvent<
      OutcomeProposedEvent.InputTuple,
      OutcomeProposedEvent.OutputTuple,
      OutcomeProposedEvent.OutputObject
    >;
    OutcomeProposed: TypedContractEvent<
      OutcomeProposedEvent.InputTuple,
      OutcomeProposedEvent.OutputTuple,
      OutcomeProposedEvent.OutputObject
    >;

    "ProposalDisputed(uint256,address,uint256)": TypedContractEvent<
      ProposalDisputedEvent.InputTuple,
      ProposalDisputedEvent.OutputTuple,
      ProposalDisputedEvent.OutputObject
    >;
    ProposalDisputed: TypedContractEvent<
      ProposalDisputedEvent.InputTuple,
      ProposalDisputedEvent.OutputTuple,
      ProposalDisputedEvent.OutputObject
    >;

    "Redeemed(uint256,address,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "Resolved(uint256,uint8)": TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;
    Resolved: TypedContractEvent<
      ResolvedEvent.InputTuple,
      ResolvedEvent.OutputTuple,
      ResolvedEvent.OutputObject
    >;

    "Swap(uint256,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
